# Generated by Django 5.1.2 on 2025-07-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pollution', 'Pollution'), ('climat', 'Climat'), ('biodiversite', 'Biodiversité'), ('energie', 'Énergie'), ('dechets', 'Déchets'), ('eau', 'Eau'), ('air', 'Air'), ('foret', 'Forêt'), ('ocean', 'Océan')], max_length=20)),
                ('keyword', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'keyword'],
            },
        ),
    ]
