# Generated by Django 5.1 on 2025-08-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_comment'),
        ('app', '0003_chathistory'),
    ]

    operations = [
    ]
