# Generated by Django 5.2.5 on 2025-08-16 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_0002_post_comment_0003_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('web', 'Web Browser'), ('flutter_android', 'Flutter Android'), ('flutter_ios', 'Flutter iOS'), ('other', 'Other')], default='web', max_length=20)),
                ('is_mobile_iteration', models.BooleanField(default=False)),
                ('session_start', models.DateTimeField(auto_now_add=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('app_open', 'App Open'), ('screen_view', 'Screen View'), ('button_click', 'Button Click'), ('chat_message', 'Chat Message'), ('post_create', 'Post Create'), ('post_like', 'Post Like'), ('comment_create', 'Comment Create')], max_length=20)),
                ('screen_name', models.CharField(blank=True, max_length=100, null=True)),
                ('element_name', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='app.usersession')),
            ],
        ),
    ]
