# Generated by Django 5.2.5 on 2025-08-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usersession_userinteraction'),
        ('app', '0006_alter_comment_options_comment_likes_comment_parent'),
    ]

    operations = [
    ]
