# Generated by Django 5.1 on 2025-08-26 23:54
# Generated by Django 5.1.3 on 2025-08-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merge_20250819_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInteraction',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
